language: java

script:
  - ant build package

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "build/tango-${TRAVIS_BRANCH}.tar.gz"
    skip_cleanup: true
    on:
      tags: true