language: java
before_install:
  - sudo apt-get install -y build-essential omniidl libomniorb4-dev libcos4-dev libomnithread3-dev libzmq3-dev  
install: ant build package
env:
  - ROOT=/home/travis/build/tango-controls/TangoSourceDistribution/build/distr

before_script: cd ${ROOT}
script:
  - ./configure
  - make all

addons:
  apt:
    update: true

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: "build/tango-${TRAVIS_BRANCH}.tar.gz"
    skip_cleanup: true
    on:
      tags: true